import JSZip from "jszip";

function sanitizeFilePath(filePath: string): string | null {
  let sanitized = filePath.replace(/^[\/\.]+/, "");
  if (sanitized.includes("..") || sanitized.includes("../")) {
    console.warn(`Rejecting file path with traversal: ${filePath}`);
    return null;
  }
  if (!/^[\w\-\/\.]+$/.test(sanitized)) {
    console.warn(`Rejecting file path with invalid characters: ${filePath}`);
    return null;
  }
  if (sanitized.startsWith("/")) sanitized = sanitized.slice(1);
  if (sanitized.length > 100) {
    console.warn(`File path too long: ${filePath}`);
    return null;
  }
  return sanitized;
}
/**
 * Generates a complete Vite + React + Tailwind project as a zip blob.
 */
export async function exportAsViteProject(
    code: string,
    files?: Record<string, string>
): Promise<Blob> {
    const zip = new JSZip();

    // package.json
    zip.file(
        "package.json",
        JSON.stringify(
            {
                name: "promptui-export",
                private: true,
                version: "1.0.0",
                type: "module",
                scripts: {
                    dev: "vite",
                    build: "vite build",
                    preview: "vite preview",
                },
                dependencies: {
                    react: "^18.3.0",
                    "react-dom": "^18.3.0",
                    "lucide-react": "latest",
                    clsx: "latest",
                    "tailwind-merge": "latest",
                },
                devDependencies: {
                    "@vitejs/plugin-react": "^4.3.0",
                    vite: "^5.4.0",
                    tailwindcss: "^3.4.0",
                    postcss: "^8.4.0",
                    autoprefixer: "^10.4.0",
                },
            },
            null,
            2
        )
    );

    // vite.config.js
    zip.file(
        "vite.config.js",
        `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
`
    );

    // tailwind.config.js
    zip.file(
        "tailwind.config.js",
        `/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: { extend: {} },
  plugins: [],
};
`
    );

    // postcss.config.js
    zip.file(
        "postcss.config.js",
        `export default {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`
    );

    // index.html
    zip.file(
        "index.html",
        `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PromptUI Export</title>
</head>
<body>
  <div id="root"></div>
  <script type="module" src="/src/main.jsx"></script>
</body>
</html>
`
    );

    // src/index.css
    zip.file(
        "src/index.css",
        `@tailwind base;
@tailwind components;
@tailwind utilities;
`
    );

    // src/main.jsx
    zip.file(
        "src/main.jsx",
        `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './index.css';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`
    );

    // Component files
    if (files && Object.keys(files).length > 1) {
        for (const [path, content] of Object.entries(files)) {
            const sanitized = sanitizeFilePath(path);
            if (!sanitized) {
                console.warn(`Skipping invalid file path: ${path}`);
                continue;
            }

            let finalPath = sanitized;
            if (!finalPath.endsWith(".jsx") && !finalPath.endsWith(".js")) {
                finalPath = finalPath.replace(/\.\w+$/, "") + ".jsx";
            }

            const srcPath = `src/${finalPath}`;

            if (!srcPath.startsWith("src/")) {
                console.warn(`Path doesn't start with src/: ${srcPath}`);
                continue;
            }

            zip.file(srcPath, content);
        }
    } else {
        zip.file("src/App.jsx", code);
    }

    // README
    zip.file(
        "README.md",
        `# PromptUI Export

Generated by [PromptUI](https://github.com/Ramnivas11/PromptUI)

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open http://localhost:5173 to see your component.
`
    );

    return zip.generateAsync({ type: "blob" });
}
